// @ts-nocheck -- skip type checking
import * as docs_7 from "../content/docs/(basic-must-knows)/wear-seatbelts-and-helmets.mdx?collection=docs&hash=1761662319555"
import * as docs_6 from "../content/docs/(basic-must-knows)/respect-speed-breakers.mdx?collection=docs&hash=1761662319555"
import * as docs_5 from "../content/docs/(basic-must-knows)/obey-speed-limits.mdx?collection=docs&hash=1761662319555"
import * as docs_4 from "../content/docs/(basic-must-knows)/follow-traffic-signals-and-road-signs.mdx?collection=docs&hash=1761662319555"
import * as docs_3 from "../content/docs/(basic-must-knows)/drive-on-the-correct-side-of-the-road.mdx?collection=docs&hash=1761662319555"
import * as docs_2 from "../content/docs/(basic-must-knows)/do-not-use-mobile-phones-while-driving.mdx?collection=docs&hash=1761662319555"
import * as docs_1 from "../content/docs/(basic-must-knows)/do-not-drink-and-drive.mdx?collection=docs&hash=1761662319555"
import * as docs_0 from "../content/docs/index.mdx?collection=docs&hash=1761662319555"
import { _runtime } from "fumadocs-mdx"
import * as _source from "../source.config"
export const docs = _runtime.docs<typeof _source.docs>([{ info: {"path":"index.mdx","absolutePath":"C:/Testing-1/code/roadha/content/docs/index.mdx"}, data: docs_0 }, { info: {"path":"(basic-must-knows)\\do-not-drink-and-drive.mdx","absolutePath":"C:/Testing-1/code/roadha/content/docs/(basic-must-knows)/do-not-drink-and-drive.mdx"}, data: docs_1 }, { info: {"path":"(basic-must-knows)\\do-not-use-mobile-phones-while-driving.mdx","absolutePath":"C:/Testing-1/code/roadha/content/docs/(basic-must-knows)/do-not-use-mobile-phones-while-driving.mdx"}, data: docs_2 }, { info: {"path":"(basic-must-knows)\\drive-on-the-correct-side-of-the-road.mdx","absolutePath":"C:/Testing-1/code/roadha/content/docs/(basic-must-knows)/drive-on-the-correct-side-of-the-road.mdx"}, data: docs_3 }, { info: {"path":"(basic-must-knows)\\follow-traffic-signals-and-road-signs.mdx","absolutePath":"C:/Testing-1/code/roadha/content/docs/(basic-must-knows)/follow-traffic-signals-and-road-signs.mdx"}, data: docs_4 }, { info: {"path":"(basic-must-knows)\\obey-speed-limits.mdx","absolutePath":"C:/Testing-1/code/roadha/content/docs/(basic-must-knows)/obey-speed-limits.mdx"}, data: docs_5 }, { info: {"path":"(basic-must-knows)\\respect-speed-breakers.mdx","absolutePath":"C:/Testing-1/code/roadha/content/docs/(basic-must-knows)/respect-speed-breakers.mdx"}, data: docs_6 }, { info: {"path":"(basic-must-knows)\\wear-seatbelts-and-helmets.mdx","absolutePath":"C:/Testing-1/code/roadha/content/docs/(basic-must-knows)/wear-seatbelts-and-helmets.mdx"}, data: docs_7 }], [{"info":{"path":"(basic-must-knows)\\meta.json","absolutePath":"C:/Testing-1/code/roadha/content/docs/(basic-must-knows)/meta.json"},"data":{"title":"Basic Must-Knows (Awareness & Obedience)","pages":["wear-seatbelts-and-helmets","follow-traffic-signals-and-road-signs","do-not-use-mobile-phones-while-driving","drive-on-the-correct-side-of-the-road","obey-speed-limits","respect-speed-breakers","do-not-drink-and-drive"],"defaultOpen":true}}])